environment:
  library: vmas
  scenario_name: navigation
  config_env:
    num_envs: 32
    device: cuda
    continuous_actions: False
    max_steps: 1000
    n_agents: 4
  wrappers: {}

  causality_config: # if empty then not causal algorithm
    config_CD:
      # path_start_knowledge:
      online_update: False
    config_CI:
      if_online_CI: False
        # others

simulation:
  training_episodes: 5000
  evaluation_episodes: 100
  seed: 42
