environment:
  library: gym
  name: FrozenLake-v1
  config:
    is_slippery: false
    reward_wrapper:
      wrapper: "scripts.environments.wrappers.FrozenLake_RewardWrapper"
      kwargs: {}
    observation_wrapper:
      wrapper: "scripts.environments.wrappers.FrozenLake_ObservationSpaceWrapper" #"scripts.environments.wrappers.Taxi_ObservationSpaceWrapper"
      kwargs:
        observation_matrix_shape: [3, 3]
        kind_of_obs: 'new'
    logging: true

algorithm:
  library: sb3  # or rllib
  name: DQN     # PPO, DQN, A3C for rllib; PPO, DQN, A2C for sb3
  hyperparameters: {}
  training_episodes: 1000
  evaluation_episodes: 100

seed: 42
