environment:
  library: gym
  name: FrozenLake-v1
  config_env: {}
  logging: true
  wrappers:
    reward_wrapper:
      wrapper: "scripts.environments.wrappers.FrozenLake_RewardWrapper"
      kwargs: {}
    observation_wrapper:
      wrapper: "scripts.environments.wrappers.FrozenLake_ObservationSpaceWrapper"
      kwargs:
        observation_matrix_shape: [3, 3]
        kind_of_obs: 'new'

algorithm:
  library: rllib
  name: ppo
  algo_config: {}

simulations:
  training_episodes: 1000
  evaluation_episodes: 100
  seed: 42
